name: Projektzaliczeniowy CI|

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip
    - name: Run Project
      run: |
        python -m .\manage.py check
        python -m .\manage.py test
        python .\main.py
    - name: Run Test
      run: |
        python -m unittest .\test.py
